name: Pylint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest numpy

      - name: Create .pylintrc
        run: |
          echo "[MASTER]" > .pylintrc
          echo "ignore-patterns=myenv/lib/python3.12/site-packages/*" >> .pylintrc
          echo "[MESSAGES CONTROL]" >> .pylintrc
          echo "disable=W0622" >> .pylintrc

      - name: Analyse the code with pylint
        run: |
          find . -type f -name "*.py" ! -path "./myenv/*" > pylint_files.txt
          xargs pylint --rcfile=.pylintrc < pylint_files.txt

      - name: Run tests
        run: pytest
